---
#
#
version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./db-dms-lite
    image: db-dms-lite
    restart: "always"
    ports:
      - "5000:5000"
    environment:
      PUID: 1000
      PGID: 1000
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_HOST: "${MYSQL_HOST}"